name: Tweet

on:
  schedule:
    - cron: "0 12 * * 0-6"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      # - run: 'echo "$consumer_key" > .env'
      #   shell: bash
      #   env:
      #     consumer_key: ${{ secrets.CONSUMER_KEY }}
      # - run: 'echo "$consumer_secret" > .env'
      #   shell: bash
      #   env:
      #     consumer_secret: ${{ secrets.CONSUMER_SECRET }}
      # - run: 'echo "$access_token" > .env'
      #   shell: bash
      #   env:
      #     access_token: ${{ secrets.ACCESS_TOKEN }}
      # - run: 'echo "access_token_secret" > .env'
      #   shell: bash
      #   env:
      #     access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET }}
      - name: set environment variables
        uses: allenevans/set-env@v1.0.0
        with:
          consumer_key: ${{ secrets.CONSUMER_KEY }}
          consumer_secret: ${{ secrets.CONSUMER_SECRET }}
          access_token: ${{ secrets.ACCESS_TOKEN }}
          access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET }}
      - name: Start server
        run: npm run start
#       - name: Test
#         env:
#           consumer_key: ${{ secrets.CONSUMER_KEY }}
#           consumer_secret: ${{ secrets.CONSUMER_SECRET }}
#           access_token: ${{ secrets.ACCESS_TOKEN }}
#           access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET }}
#         run: |
#           echo ${#consumer_key}
#           echo ${#access_token}
# - run: npm run start
#         env:
#           consumer_key: ${{ secrets.CONSUMER_KEY }}
#           consumer_secret: ${{ secrets.CONSUMER_SECRET }}
#           access_token: ${{ secrets.ACCESS_TOKEN }}
#           access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET }}
